version: "3.9"

services:
  bot:
    build: .
    env_file:
      - .env
    command: cargo run --release
  
  confirm-alive:
    build: .
    env_file:
      - .env
    entrypoint: /app/confirm-alive.sh

  send-alerts:
    build: .
    env_file:
      - .env
    entrypoint: /app/send-alerts.sh
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
